on:
  push:
    branches:
      - master













jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "login"
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.TOKEN }}     
      - name: "Build docker image"
        run: docker build -t ${{ secrets.USERNAME }}/myimage .

      - name: " pushing to docker hub"
        run: docker push ${{ secrets.USERNAME }}/myimage 
















